
# Write a function so that the columns of the output matrix are powers of the inputvector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N -i -1.HINT:  Such  a  matrix  with  a  geometric  progression  in  each  row  is  named  for  Alexandre-Theophile Vandermonde.

In [49]:
import numpy as np
x = np.array([1, 2, 3, 5])

N = 3

m=np.vander(x, N)
m

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [50]:
m1=np.column_stack([x**(N-1-i) for i in range(N)])
m1

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:The moving average sequence has n-k+1 elements as shown below.The moving averages with k=4 of a ten-value sequence (n=10) is shown belowi1  2  3  4  5  6  7  8  9 10======= == == == == == == == == ==Input 10 20 30 40 50 60 70 80 90 100 y125 = (10+20+30+40)/4y235 = (20+30+40+50)/4y345 = (30+40+50+60)/4y455 = (40+50+60+70)/4y565 = (50+60+70+80)/4y675 = (60+70+80+90)/4y785 = (70+80+90+100)/4Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question:Write a function to find moving average in an array over a window:Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [65]:
def moving_average(x, w):
    return np.convolve(x, np.ones(w)) / w

In [66]:
import numpy as np
a = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [67]:
moving_average(a,3)

array([  1.        ,   2.66666667,   5.        ,   4.66666667,
         5.66666667,   6.66666667,   9.66666667,  28.66666667,
        49.33333333,  72.66666667,  84.        ,  93.33333333,
       116.33333333,  83.33333333,  50.        ])

In [68]:
np.ones(3)

array([1., 1., 1.])

In [69]:
np.convolve(a, np.ones(w), 'valid') / w

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [70]:
a


array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [83]:
asum=np.cumsum(a)
n=3
print(asum)
len(a)

[  3   8  15  17  25  35  46 111 183 264 363 463 613]


13

In [77]:
asum[n:]

array([ 17,  25,  35,  46, 111, 183, 264, 363, 463, 613], dtype=int32)

In [84]:
asum[:-n]

array([  3,   8,  15,  17,  25,  35,  46, 111, 183, 264], dtype=int32)

In [80]:
asum[n:] = asum[n:]-asum[:-n]

In [82]:
asum[n-1:]/3

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [86]:
def moving_ave(x,w):
    asum= np.cumsum(x)
    asum[n:]=asum[n:]-asum[:-n]
    return asum[n-1:]/n

In [87]:
moving_ave(a,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])